arch:
   - amd64
   - ppc64le
language: python
python:
#  - 2.6
  - 2.7
  - 3.3
  - 3.4
matrix:
   allow_failures:
      - python: 3.3 #EOL
install: 
script: python setup.py test
os:
    - linux
#    - osx
